version: '3.8'

services:
  stop-watch:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
      - "3001:3001"
    tty: true
    stdin_open: true
    volumes:
      - ./docs:/app
    command: yarn start
